type Query{
    getUsers(page:Int,size:Int):ContentPageable!
    getUserById(id:ID!): User
    getMovieByName(userId:ID!,name:String!): [Movie]!
    getAllMovies(page:Int,size:Int): [MovieResponse]!
}

type ContentPageable{
    content:[User]!
    hasNext:Boolean!
    hasPrevious:Boolean!
    actualPage:Int!
    size:Int!
    offSet:Int!
    totalPage:Int!
}

type Mutation{
    addUser(userInput:UserInput!): User!
    updateUser(id:ID!, userInput:UserInput!): User!
    deleteUser(id:ID!): Boolean
}

type MovieResponse{
    userId:ID!
    name:String!
    releaseYear:Int!
}

type Movie {
    name : String!
    releaseYear : Int!
}

type User{
    id: ID!
    name: String!
    email: String!
    age: Int!
    movies: [Movie]
}

input UserInput{
    name: String!
    email: String!
    age: Int!
}