spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/group42Labs"
          jwk-set-uri: "http://localhost:8080/realms/group42Labs/protocol/openid-connect/certs"
      client:
        registration:
          auth0:
            client-id: d6RuGCnxgpl9Zymd8fqZv9PpghwNq7u3
            client-secret: IQuGwngaQjY-plL4Gj8cZRHbKOSlNz3vgenQOFwwtjXd5qn7VWvEmsXmmYH77n_v
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Auth0
            provider: auth0
        provider:
          auth0:
            issuer-uri: https://dev-jojnaxokblh5ssmo.us.auth0.com/
            authorization-uri: https://dev-jojnaxokblh5ssmo.us.auth0.com/authorize
            token-uri: https://dev-jojnaxokblh5ssmo.us.auth0.com/oauth/token
            user-info-uri: https://dev-jojnaxokblh5ssmo.us.auth0.com/userinfo
            user-name-attribute: sub
  application:
    name: graphql
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    graphiql:
      enabled: true
server:
  port: 8084

